title: The Quilt Project
short_title: Quilt
description: The mod-loader that cares.
baseurl: ""
url: "https://quiltmc.org"
source: "src/"
permalink: pretty
author: QuiltMC

paginate_path: "/blog/p/:num/"
paginate: 5

# Social media handles
twitter_username: quilt_mc
github_username: QuiltMC
gitlab_username: quiltmc
twitch_username: quiltmc
discord_community: https://discord.quiltmc.org
discord_toolchain: https://discord.quiltmc.org/toolchain

twitter:
  username: quilt_mc
  card: summary

logo: /assets/img/logo-square.png

social:
  name: QuiltMC

  links:
    - https://twitter.com/quilt_mc
    - https://github.com/QuiltMC
    - https://twitch.tv/quiltmc

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-seo-tag

collections:
  about:
    permalink: /about/:path/
    output: true

  community:
    permalink: /community/:path/
    output: true

  posts:
    permalink: "/blog/:year/:month/:day/:title/"

    order:
      - index.md

  staff:
    permalink: /staff/:path/
    output: true

defaults:
  -
    scope:
      path: ""
      type: "about"
    values:
      layout: "about-page"

  -
    scope:
      path: ""
      type: "community"
    values:
      layout: "community-document"

  -
    scope:
      path: ""
      type: "staff"
    values:
      layout: "staff-document"

  -
    scope:
      path: ""
    values:
      layout: "default"
      excerpt_separator: "<!-- MORE -->"
      image: /assets/img/logo-square.png

  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      seo:
        type: BlogPosting

  -
    scope:
      path: ""
      type: "wiki"
    values:
      layout: "wiki-page"

  # Mark pages private until full launch

  -
    scope:
      path: "install/*"
    values:
      private: true

  -
    scope:
      path: "dev/*"
    values:
      private: true

  -
    scope:
      path: ""
      type: "wiki"
    values:
      private: true

sass:
    sass_dir: _sass
