title: The Quilt Project
short_title: Quilt
description: >-
  The Quilt project is an open, community-driven modding toolchain designed
  primarily for Minecraft.
baseurl: ""
url: ""
source: "src/"

# Social media handles
twitter_username: quilt_mc
github_username:  QuiltMC
gitlab_username: quiltmc
twitch_username: quiltmc
discord_community: https://discord.quiltmc.org
discord_toolchain: https://discord.quiltmc.org/toolchain

plugins:
  - jekyll-feed
  - jekyll-redirect-from

collections:
  community:
    permalink: /community/:title:output_ext
    output: true
  posts:
    permalink: /blog/:year/:month/:day/:title:output_ext
    order:
      - index.md
  wiki:
    permalink: /wiki/:title:output_ext
    output: true
    order:
      - index.md
      - rules.md
      - code-of-conduct.md
      - moderation.md

defaults:
  -
    scope:
      path: ""
      type: "community"
    values:
      layout: "community-document"
    order:
      index.md
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "wiki"
    values:
      layout: "wiki-page"
  # Mark pages private until full launch
  -
    scope:
      path: "install/*"
    values:
      private: true
  -
    scope:
      path: "dev/*"
    values:
      private: true
  -
    scope:
      path: ""
      type: "wiki"
    values:
      private: true


sass:
    sass_dir: _sass
