title: The Quilt Project
short_title: Quilt
description: The mod-loader that cares.
baseurl: ""
url: "https://quiltmc.org"
source: "src/"
permalink: pretty

# Social media handles
twitter_username: quilt_mc
github_username: QuiltMC
gitlab_username: quiltmc
twitch_username: quiltmc
discord_community: https://discord.quiltmc.org
discord_toolchain: https://discord.quiltmc.org/toolchain

twitter:
  username: quilt_mc
  card: summary

logo: /assets/logo-square.png

social:
  name: QuiltMC

  links:
    - https://twitter.com/quilt_mc
    - https://github.com/QuiltMC
    - https://twitch.tv/quiltmc

plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag

collections:
  about:
    permalink: /about/:title/
    output: true
  community:
    permalink: /community/:title/
    output: true
  posts:
    permalink: /blog/:year/:month/:day/:title/
    order:
      - index.md

defaults:
  -
    scope:
      path: ""
      type: "about"
    values:
      layout: "about-page"
    order:
      index.md
  -
    scope:
      path: ""
      type: "community"
    values:
      layout: "community-document"
    order:
      index.md
  -
    scope:
      path: ""
    values:
      layout: "default"
      excerpt_separator: "<!-- MORE -->"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      seo:
        type: BlogPosting
  -
    scope:
      path: ""
      type: "wiki"
    values:
      layout: "wiki-page"
  # Mark pages private until full launch
  -
    scope:
      path: "install/*"
    values:
      private: true
  -
    scope:
      path: "dev/*"
    values:
      private: true
  -
    scope:
      path: ""
      type: "wiki"
    values:
      private: true

sass:
    sass_dir: _sass
