overrides:
  svgo: ^4.0.1
  unicorn-magic: ^0.4.0
allowBuilds:
  '@parcel/watcher': true
  '@scarf/scarf': true
  '@tree-sitter-grammars/tree-sitter-yaml': true
  core-js-pure: true
  esbuild: true
  sharp: true
  tree-sitter: true
  tree-sitter-json: true
  workerd: false
  astro-i18next@https://codeload.github.com/quiltmc/astro-i18next/tar.gz/9208ed1197a6a10c96b7a49713b1eb60ec8fd9aa: true
