name: Bug Report
description: Create a bug report to help us fix issues with the Quilt website.
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking your time to report this bug! If you need real-time help, join us on [Discord](https://discord.quiltmc.org).

  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: "Describe the bug as clearly as possible. The more detail you provide means the sooner the bug can be fixed! This includes: steps to reproduce or situation you encountered the bug in, or any additional context that could be helpful."
    validations:
      required: true

  - type: dropdown
    id: environment
    attributes:
      label: Which browser are you using?
      options:
        - Firefox
        - Chrome
        - Edge
        - Opera
        - Vivaldi
        - Brave
    validations:
      required: true
