name: Content Issue Report
description: Report a content issue on the website.
labels: [content issue]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking your time to report this content issue! If you need real-time help, join us on [Discord](https://discord.quiltmc.org).

  - type: textarea
    id: description
    attributes:
      label: Describe the issue
      description: "Please describe the content issue you found."
    validations:
      required: true

  - type: textarea
    id: device-and-os
    attributes:
      label: What device are you using and what OS is it running?
    validations:
      required: true

  - type: textarea
    id: browser
    attributes:
      label: Which browser are you using? If you know your browser version, please specify it.
      description: "Please be sure you're on the latest version of the browser you are currently using."
    validations:
      required: true
