name: Feature Request
description: Suggest a new feature or improvement for the website.
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking your time to create your feature request! If you want to discuss your request, join us on [Discord](https://discord.quiltmc.org).

  - type: textarea
    id: description
    attributes:
      label: Describe what feature(s) you want.
      description: "Describe the enhancement in as much detail as possible. What does it do? What problem does it solve? How might it work?"
    validations:
      required: true

  - type: textarea
    id: additional-info
    attributes:
      label: Additional Information
      description: "Add any other information about your feature request here."
