on: [push, workflow_call]
name: Commit preview

jobs:
  comment-on-commit:
      name: Add a comment on the commit
      runs-on: ubuntu-latest
      permissions:
        contents: read
      env:
        DEPLOYMENT_URL: http://example.com
      steps:
          - name: Comment on the Comment
            uses: peter-evans/commit-comment@v4 # v3.0.0
            with:
              token: ${{ github.token }}
              body: "See the preview on Cloudflare: ${{ env.DEPLOYMENT_URL }}\nBranch URL: https://${{ github.ref_name }}-quiltmc-org.quiltmc.workers.dev"
