on:
  push:
  workflow_call:
    inputs:
      wrangler-config-path:
        required: false
        default: dist/server/wrangler.json
        type: string

name: Commit preview

jobs:
  build-website:
    uses: ./.github/workflows/build-website.yaml

  publish:
    uses: ./.github/workflows/publish-website.yaml
    needs: build-website
    secrets: inherit
    permissions:
      actions: read
      contents: read
    with:
      deploy: ${{ github.ref_name == 'main' }}
      wrangler-config-path: ${{ inputs.wrangler-config-path }}

  comment-on-commit:
      name: Add a comment on the commit
      runs-on: ubuntu-latest
      needs: publish
      env:
        DEPLOYMENT_URL: ${{ needs.publish.outputs.deployment-url }}
      steps:
          - name: Comment on the Comment
            uses: peter-evans/commit-comment@v4
            with:
              body: "See the preview on Cloudflare: ${{ env.DEPLOYMENT_URL }}\nBranch URL: https://${{ github.ref_name }}-quiltmc-org.quiltmc.workers.dev"
