on: workflow_dispatch
name: Manual publish

jobs:
  build-website:
    uses: ./.github/workflows/build-website.yml
  
  publish:
    uses: ./.github/workflows/publish.yml
    needs: build-website
    secrets: inherit