on: [workflow_dispatch, workflow_call]
name: Manual publish

jobs:
  build-website:
    uses: ./.github/workflows/build-website.yaml

  publish:
    uses: ./.github/workflows/publish-website.yaml
    needs: build-website
    secrets: inherit
    permissions:
      actions: read
      contents: read
    with:
      deploy: true
