on: workflow_dispatch
name: Manual publish

jobs:
  build-website:
    uses: ./.github/workflows/build-website.yaml
  
  publish:
    uses: ./.github/workflows/publish.yaml
    needs: build-website
    secrets: inherit