on:
  pull_request_target:
    types: [opened]
  workflow_call:
    inputs:
      preview-domain:
        type: string
        required: false
name: Add footer to PR

jobs:
  comment:
    name: Add preview footer to PR
    runs-on: ubuntu-latest

    steps:
      - name: Add preview footer to PR
        uses: devindford/Append_PR_Comment@main
        with:
          repo-token: "${{ github.token }}"
          body-template: |
            ---
            See preview on Cloudflare Pages: https://preview-${{ github.event.number }}-${{ inputs.preview-domain || 'quiltmc-org.quiltmc.workers.dev' }}
          body-update-action: "suffix"
