on:
  workflow_call:
    inputs:
      branch:
        required: false
        default: ${{ github.ref_name }}
        type: string
      run-id:
        required: false
        default: ${{ github.run_id }}
        type: string
    outputs:
      deployment-url:
        description: The URL of the deployed site.
        value: ${{ jobs.publish.outputs.deployment-url }}

jobs:
  publish:
    name: "Publish to Cloudflare Pages"
    runs-on: ubuntu-latest
    outputs:
      deployment-url: ${{ steps.cloudflare-publish.outputs.deployment-url }}
    permissions:
      contents: read
    env:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      GITHUB_RUN_ID: ${{ inputs.run-id }}
      GITHUB_TOKEN: ${{ secrets.COZY_PAT }}
    steps:
      - name: Download Website HTML
        uses: actions/download-artifact@v4
        with:
          name: html
          path: dist
          run-id: ${{ env.GITHUB_RUN_ID }}
          github-token: ${{ env.GITHUB_TOKEN }}
      - name: Download Website Functions
        uses: actions/download-artifact@v4
        with:
          name: functions
          path: functions
          run-id: ${{ env.GITHUB_RUN_ID }}
          github-token: ${{ env.GITHUB_TOKEN }}
      - name: Publish to Cloudflare Pages
        id: cloudflare-publish # This step needs an ID because its outputs may be needed in subsequent jobs.
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ env.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ env.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy dist --project-name quiltmc-org --branch ${{ inputs.branch }}
