on:
  workflow_run:
    workflows: ["Generate PR preview"]
    types: [completed]

jobs:
  test:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: crazy-max/ghaction-dump-context@v2
